"""initial schema

Revision ID: 953ae77b8e8b
Revises: 
Create Date: 2026-06-04 21:37:44.569199
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '953ae77b8e8b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=80), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='cascade'
    )
    op.create_table('orgs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    schema='cascade'
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='cascade'
    )
    op.create_index(op.f('ix_cascade_users_email'), 'users', ['email'], unique=True, schema='cascade')
    op.create_table('memberships',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), server_default=sa.text("'viewer'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role in ('owner', 'editor', 'viewer')", name='ck_membership_role'),
    sa.ForeignKeyConstraint(['org_id'], ['cascade.orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['cascade.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'user_id', name='uq_membership_org_user'),
    schema='cascade'
    )
    op.create_table('provider_keys',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=40), server_default=sa.text("'openrouter'"), nullable=False),
    sa.Column('encrypted_key', sa.Text(), nullable=False),
    sa.Column('last4', sa.String(length=8), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['cascade.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['cascade.orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cascade'
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['cascade.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cascade'
    )
    op.create_index(op.f('ix_cascade_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True, schema='cascade')
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_sample', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['cascade.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['cascade.orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cascade'
    )
    op.create_table('runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('trigger', sa.String(length=20), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('claimed_by', sa.String(length=80), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_key_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('queued', 'running', 'succeeded', 'failed', 'canceled')", name='ck_run_status'),
    sa.CheckConstraint("trigger in ('manual', 'sample')", name='ck_run_trigger'),
    sa.ForeignKeyConstraint(['created_by'], ['cascade.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['cascade.orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_key_id'], ['cascade.provider_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['cascade.workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='cascade'
    )
    op.create_index('ix_runs_org_created', 'runs', ['org_id', 'created_at'], unique=False, schema='cascade')
    op.create_index('ix_runs_status_created', 'runs', ['status', 'created_at'], unique=False, schema='cascade')
    op.create_table('workflow_steps',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type in ('http_fetch', 'llm', 'transform', 'conditional', 'output')", name='ck_step_type'),
    sa.ForeignKeyConstraint(['workflow_id'], ['cascade.workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'position', name='uq_step_workflow_position'),
    schema='cascade'
    )
    op.create_table('step_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('logs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('pending', 'running', 'succeeded', 'failed', 'skipped')", name='ck_step_run_status'),
    sa.ForeignKeyConstraint(['run_id'], ['cascade.runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['cascade.workflow_steps.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='cascade'
    )
    op.create_index('ix_step_runs_run_position', 'step_runs', ['run_id', 'position'], unique=False, schema='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_step_runs_run_position', table_name='step_runs', schema='cascade')
    op.drop_table('step_runs', schema='cascade')
    op.drop_table('workflow_steps', schema='cascade')
    op.drop_index('ix_runs_status_created', table_name='runs', schema='cascade')
    op.drop_index('ix_runs_org_created', table_name='runs', schema='cascade')
    op.drop_table('runs', schema='cascade')
    op.drop_table('workflows', schema='cascade')
    op.drop_index(op.f('ix_cascade_refresh_tokens_token_hash'), table_name='refresh_tokens', schema='cascade')
    op.drop_table('refresh_tokens', schema='cascade')
    op.drop_table('provider_keys', schema='cascade')
    op.drop_table('memberships', schema='cascade')
    op.drop_index(op.f('ix_cascade_users_email'), table_name='users', schema='cascade')
    op.drop_table('users', schema='cascade')
    op.drop_table('orgs', schema='cascade')
    op.drop_table('audit_log', schema='cascade')
    # ### end Alembic commands ###
